---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: latest

inputs:
  - name: dp-healthcheck
    path: dp-healthcheck

run:
  path: dp-healthcheck/ci/scripts/build.sh
